services:
  garden:
    build:
      context: .
      dockerfile: garden.Dockerfile
      target: base
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    device:
      - /dev/dri
    network_mode: host  # Use host networking
    stdin_open: true
    tty: true
    command: gz sim